# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    import requests
import pandas as pd
import time
"""

import requests
import pandas as pd
import time
import pandas as pd
import time

# =====================================
# TELEGRAM
# =====================================
TOKEN = "8229091266:AAHzWGVuzi_F4KCiJ1naL7_knKPBr21E93k"
CHAT_ID = " 729720320"

# =====================================
# TWELVE DATA
# =====================================
API_KEY = "8ddb1cdc9051436b8fc9bfd775b913fc"

# =====================================
# SETTINGS
# =====================================
SYMBOL = "EUR/USD"
INTERVAL = "1h"
OUTPUTSIZE = 200

AUTO_TRADE = False
CHECK_INTERVAL = 3600
RISK_REWARD = 2

def get_market_data():
    url = (
        "https://api.twelvedata.com/time_series"
        f"?symbol={SYMBOL}"
        f"&interval={INTERVAL}"
        "&outputsize=200"
        f"&apikey={API_KEY}"
    )

    response = requests.get(url, timeout=20)
    data = response.json()

    if "values" not in data:
        print(data)
        return None

    df = pd.DataFrame(data["values"])

    df = df.iloc[::-1].reset_index(drop=True)

    for col in ["open", "high", "low", "close"]:
        df[col] = df[col].astype(float)

    return df


df = get_market_data()

if df is not None:
    print(df.tail())

def calculate_indicators(df):
    # EMA 20
    df["EMA20"] = df["close"].ewm(span=20, adjust=False).mean()

    # EMA 50
    df["EMA50"] = df["close"].ewm(span=50, adjust=False).mean()

    # RSI 14
    delta = df["close"].diff()

    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)

    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()

    rs = avg_gain / avg_loss
    df["RSI"] = 100 - (100 / (1 + rs))

    # MACD
    ema12 = df["close"].ewm(span=12, adjust=False).mean()
    ema26 = df["close"].ewm(span=26, adjust=False).mean()

    df["MACD"] = ema12 - ema26
    df["MACD_SIGNAL"] = df["MACD"].ewm(span=9, adjust=False).mean()

    return df


df = calculate_indicators(df)

print(df[[
    "close",
    "EMA20",
    "EMA50",
    "RSI",
    "MACD",
    "MACD_SIGNAL"
]].tail())

def generate_signal(df):
    last = df.iloc[-1]

    if (
        last["EMA20"] > last["EMA50"] and
        last["MACD"] > last["MACD_SIGNAL"] and
        last["RSI"] > 50
    ):
        signal = "BUY"

    elif (
        last["EMA20"] < last["EMA50"] and
        last["MACD"] < last["MACD_SIGNAL"] and
        last["RSI"] < 50
    ):
        signal = "SELL"

    else:
        signal = "WAIT"

    print("=" * 40)
    print("SIGNAL :", signal)
    print("PRICE  :", last["close"])
    print("EMA20  :", round(last["EMA20"], 5))
    print("EMA50  :", round(last["EMA50"], 5))
    print("RSI    :", round(last["RSI"], 2))
    print("MACD   :", round(last["MACD"], 5))
    print("SIGNAL :", round(last["MACD_SIGNAL"], 5))
    print("=" * 40)

    return signal


generate_signal(df)

BOT_TOKEN = "8229091266:AAHzWGVuzi_F4KCiJ1naL7_knKPBr21E93k"
CHAT_ID = "729720320"

def send_telegram(message):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

    data = {
        "chat_id": CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"
    }

    response = requests.post(url, data=data)
    return response.json()


signal = generate_signal(df)

last = df.iloc[-1]

message = f"""
📈 *Forex Signal*

💱 الزوج: {SYMBOL}

📢 الإشارة: {signal}

💰 السعر: {last['close']:.5f}

📊 RSI: {last['RSI']:.2f}
📈 EMA20: {last['EMA20']:.5f}
📉 EMA50: {last['EMA50']:.5f}

⚙️ MACD: {last['MACD']:.5f}
⚙️ Signal: {last['MACD_SIGNAL']:.5f}
"""

result = send_telegram(message)

print(result)

import time

print("🚀 بدأ البوت...")

while True:
    try:
        df = get_market_data()

        if df is not None:
            df = calculate_indicators(df)
            signal = generate_signal(df)

            last = df.iloc[-1]

            message = f"""
📈 *Forex Signal*

💱 الزوج: {SYMBOL}

📢 الإشارة: {signal}

💰 السعر: {last['close']:.5f}

📊 RSI: {last['RSI']:.2f}
📈 EMA20: {last['EMA20']:.5f}
📉 EMA50: {last['EMA50']:.5f}

⚙️ MACD: {last['MACD']:.5f}
⚙️ Signal: {last['MACD_SIGNAL']:.5f}
"""

            print(send_telegram(message))

        print("⏳ انتظار ساعة...")
        time.sleep(CHECK_INTERVAL)

    except Exception as e:
        print("ERROR:", e)
        time.sleep(60)
